### ISSUE TITLE
BPG-XnView-0.0.0.2 crashes xnview

### ISSUE THREAD

**Issue by mausalimi** [leavinel/BPG-Plugins#1]
hi,

as the title says.

> Problemereignisname:  APPCRASH
>   Anwendungsname:   xnview.exe
>   Anwendungsversion:    2.34.0.0
>   Anwendungszeitstempel:    55ed9448
>   Fehlermodulname:  Xbpg.usr
>   Fehlermodulversion:   0.0.0.2
>   Fehlermodulzeitstempel:   03be4e90
>   Ausnahmecode: c0000091
>   Ausnahmeoffset:   00287812
>   Betriebsystemversion: 6.1.7601.2.1.0.256.1
>   Gebietsschema-ID: 2055
>   Zusatzinformation 1:  0a9e
>   Zusatzinformation 2:  0a9e372d3b4ad19135b953a78882e789
>   Zusatzinformation 3:  0a9e
>   Zusatzinformation 4:  0a9e372d3b4ad19135b953a78882e789

thanks for your effort. :+1:

**Comment by leavinel** [comment]
Hi,

Your information does not help. (It just says I'm crashed)

Did XnView crash when reading or writing BPG?
Or you can attach the problem image file.  I will try to reproduce it.

**Comment by mausalimi** [comment]
open .bpg files works fine.

but for a lot of images xnview crashes when saving.
![stitcher](https://cloud.githubusercontent.com/assets/1296426/11347708/06d573fa-9223-11e5-85ba-db130192bed3.png)
![mutton_cove_abel_tasman](https://cloud.githubusercontent.com/assets/1296426/11347701/0167fe2e-9223-11e5-94d7-245e8ba93a72.jpg)
![sandfly_bay](https://cloud.githubusercontent.com/assets/1296426/11347687/f8da3830-9222-11e5-8d01-eec664f2ab84.jpg)
![a_004](https://cloud.githubusercontent.com/assets/1296426/11347677/e6785b72-9222-11e5-9e22-2ca6aedb5d39.jpg)

most images i tried xnviews hang for > 1 minute and then crashes.
stitcher.png (the one on the top), crashes right after start saving.

btw,i'm using xnview 2.34,as shown in the error log.

**Comment by mausalimi** [comment]
anyone tested these?

i'm just nosy if it's a problem at my end.

**Comment by leavinel** [comment]
Just tried on XnView 2.32 32-bit
My Xbpg.ini:

```
24:-q 25 -e x265
8:-q 35 -e jctvc
```
- Img1: A 8-bit color image.  Convert to 24-bit before write.
- Img2&3: They are definitely big.  Took long time (~10 sec) on my E6600 but saved successfully.
- Img4: A 32-bit image.  Convert to 24-bit before write.

Please note that this BPG plugin does not come with a smart color converter.
8-bit mode is for greyscale only.

**Comment by mausalimi** [comment]
ah,i see.

with your .ini it works here too.
img4 is 24bit when i download it from here (no idea why), and it works then too.

it would be nice if we could set the options in xnview... but that's s not your part.

thanks.
