### ISSUE TITLE
x64-plugin for Imagine

### ISSUE THREAD

**Issue by Skif-off** [leavinel/BPG-Plugins#2]
Could you add x64-plugin for Imagine?

**Comment by leavinel** [comment]
Hi,

Sorry that I haven't make x64 compiler work on my PC.
I will release x64 version once prepared.

**Comment by mausalimi** [comment]
http://encode.ru/threads/2095-BPG-yet-another-format-to-replace-JPEG?p=50596&viewfull=1#post50596

**Comment by leavinel** [comment]
x64 compile released [0.0.0.5](https://github.com/leavinel/BPG-Plugins/releases/tag/v0.0.0.5)
