### ISSUE TITLE
loseless

### ISSUE THREAD

**Issue by frank-e** [leavinel/BPG-Plugins#3]
Hi, I'm testing your Xbpg.usr plugin for XnView (32bits image viewer on a 64bits Windows 7 box). Read access works, but write access needs more documentation: What is the format of Xbpg.ini?  So far I think your "loseless" might not match BPGenc "lossless", and -lossless -q 1 -m 9 -e jctvc is precisely what I want.

Guessing, you just use some BPGenc.exe 0.95 or 0.96 within Xbpg.usr, i.e., you can only do PNG or JPG, is that correct? The BPG-plugins-master/libbpg-0.9.5 folder in a downloaded BPG-plugins-master.zip is empty.  I don't know C++ and gave up to guess what happens near line 198 in src/writer.cpp

**Comment by leavinel** [comment]
Hi,

The following is an example of Xbpg.ini:

```
24: -lossless -q1 -m9 -e -x265
8: -e jctvc
```

The options are listed in README.md.  You can modify for yourself.

Xbpg.usr uses partial modified source code from bpgenc.exe. However, it does not include PNG / JPG decoding.  XnView itself can do such work.

BPG-plugins-master/libbpg-0.9.5 is a GIT sub-project, which links to another GIT repo.
Check https://github.com/leavinel/libbpg-mod.
