### ISSUE TITLE
cannot compile 0.0.0.3

### ISSUE THREAD

**Issue by mausalimi** [leavinel/BPG-Plugins#4]
what am i doing wrong?

> src/bpg_common.hpp:67:25: error: 'BPGDecodeBuffer' was not declared in this scope
>  typedef std::shared_ptr<BPGDecodeBuffer> pBPGDecoderBuffer;
>                          ^
> src/bpg_common.hpp:67:40: error: template argument 1 is invalid
>  typedef std::shared_ptr<BPGDecodeBuffer> pBPGDecoderBuffer;
>                                         ^
> src/bpg_common.hpp:103:21: error: 'BPGDecodeBuffer' was not declared in this scope
>      std::shared_ptr<BPGDecodeBuffer> buf;
>                      ^
> src/bpg_common.hpp:103:36: error: template argument 1 is invalid
>      std::shared_ptr<BPGDecodeBuffer> buf;
>                                     ^
> src/bpg_common.hpp:162:21: error: 'BPGEncoderParameters' was not declared in this scope
>      std::shared_ptr<BPGEncoderParameters> param;
>                      ^
> src/bpg_common.hpp:162:41: error: template argument 1 is invalid
>      std::shared_ptr<BPGEncoderParameters> param;
>                                          ^
> src/bpg_common.hpp:175:5: error: 'BPGEncoderParameters' does not name a type
>      BPGEncoderParameters\* operator->() {
>      ^
> src/bpg_common.hpp:179:14: error: 'BPGEncoderParameters' does not name a type
>      operator BPGEncoderParameters_() const {
>               ^
> src/bpg_common.hpp:234:21: error: 'BPGEncoderContext' was not declared in this scope
>      std::shared_ptr<BPGEncoderContext> ctx;
>                      ^
> src/bpg_common.hpp:234:38: error: template argument 1 is invalid
>      std::shared_ptr<BPGEncoderContext> ctx;
>                                       ^
> src/xnview/Xbpg.cpp: In member function 'void BpgReader::fullDecode()':
> src/xnview/Xbpg.cpp:143:15: error: 'BPG_OUTPUT_FORMAT_GRAY8' was not declared in this scope
>          fmt = BPG_OUTPUT_FORMAT_GRAY8;
>                ^
> src/xnview/Xbpg.cpp: In member function 'void BpgWriter::Write()':
> src/xnview/Xbpg.cpp:314:18: error: base operand of '->' has non-pointer type 'bpg::EncParam'
>              param->preferred_chroma_format = BPG_FORMAT_GRAY;
>                   ^
> make: *_\* [obj/xnview/Xbpg.cpp.o] Error 1

**Comment by leavinel** [comment]
It looks like that your compiler can't find libbpg.h.
Check your include path.
