### ISSUE TITLE
XnView plugin error read bpg when height < 128 pixel

### ISSUE THREAD

**Issue by ErinQvnm** [leavinel/BPG-Plugins#5]
It works well with bpgview.exe, with your plugin xnview crashes. Could you please fix it?

**Comment by leavinel** [comment]
Hi,
I just tried to make a small bpg image with height 121px and opened successfully.
Can you attach your bpg file?

**Comment by ErinQvnm** [comment]
Here the file,
[Clipboard 1.tar.gz](https://github.com/leavinel/BPG-Plugins/files/559767/Clipboard.1.tar.gz)
Sorry i used .gz because github refuses upload .bpg and .zip. I include both jpg and bpg in case you need them.

**Comment by leavinel** [comment]
Tested ok on [0.0.0.5](https://github.com/leavinel/BPG-Plugins/releases/tag/v0.0.0.5)
