### ISSUE TITLE
Irfanview plugin

### ISSUE THREAD

**Issue by ianamk** [leavinel/BPG-Plugins#6]
according to
http://www.irfanview.com/plugins.htm

> For developers: If you want to write your own plugins for IrfanView (support for new image formats or effects (please no private formats)), please send me an email for details. 

irfan's email can be found on iirfanview's homepage 
http://www.irfanview.com/
it's in the frame in top right corner
there is a forum thread about bpg plugiin but as I understood it it was a read only plugin and it will not be released to the public because of bpg's patent issues so a 3rd party release is the only way to get it
https://irfanview-forum.de/showthread.php?t=10291

**Comment by leavinel** [comment]
Hi,
You are welcome to use my code to implement IrfanView plug-in
