### ISSUE TITLE
x64 bit compilation errors

### ISSUE THREAD

**Issue by ianamk** [leavinel/BPG-Plugins#7]
I'm truing to compile with the current  x64 bit version of gcc 7.2.0 from
https://github.com/msys2/msys2/wiki/MSYS2-installation
unfortunately I'm getting quite a few errors and I'm no programmer never even had a course in C++
any suggestions (or maybe a 64bit compile?)
> $ make
mkdir -p obj/imagine/
g++ -c -DUSE_JCTVC -DUSE_X265 -Ilibbpg-0.9.5 -Isrc -std=c++11 -MMD -MF obj/imagine/bpg.cpp.d -Wall -O2  src/imagine/bpg.cpp -o obj/imagine/bpg.cpp.o
In file included from src/threadpool.hpp:16:0,
                 from src/bpg_common.hpp:30,
                 from src/imagine/bpg.cpp:11:
src/winthread.hpp: In member function 'unsigned int winthread::thread::procedure()':
src/winthread.hpp:208:47: error: cast from 'winthread::thread*' to 'unsigned in ' loses precision [-fpermissive]
         return reinterpret_cast<unsigned>(this);
                                               ^
src/imagine/bpg.cpp: In function 'BOOL checkFile(IMAGINEPLUGINFILEINFOTABLE*, IMAGINELOADPARAM*, int)':
src/imagine/bpg.cpp:55:12: error: 'BpgImageInfo2' has not been declared
     return BpgImageInfo2::CheckHeader (loadParam->buffer, loadParam->length);
            ^~~~~~~~~~~~~
src/imagine/bpg.cpp: In function 'void* loadFile(IMAGINEPLUGINFILEINFOTABLE*, IMAGINELOADPARAM*, int)':
src/imagine/bpg.cpp:68:13: error: 'BpgImageInfo2' was not declared in this scope
             BpgImageInfo2 info;
             ^~~~~~~~~~~~~
src/imagine/bpg.cpp:68:13: note: suggested alternative: 'BPGImageInfo'
             BpgImageInfo2 info;
             ^~~~~~~~~~~~~
             BPGImageInfo
src/imagine/bpg.cpp:69:13: error: 'info' was not declared in this scope
             info.LoadFromBuffer (loadParam->buffer, loadParam->length);
             ^~~~
src/imagine/bpg.cpp:69:13: note: suggested alternative: 'int'
             info.LoadFromBuffer (loadParam->buffer, loadParam->length);
             ^~~~
             int
src/imagine/bpg.cpp:71:13: error: 'Logi' was not declared in this scope
             Logi ("%s [%ux%u] @ %u bpp flags%X\n", __FUNCTION__, info.width, info.height, bpp, flags);
             ^~~~
src/imagine/bpg.cpp:82:9: error: 'BpgReader' was not declared in this scope
         BpgReader reader;
         ^~~~~~~~~
src/imagine/bpg.cpp:83:9: error: 'reader' was not declared in this scope
         reader.LoadFromBuffer (loadParam->buffer, loadParam->length);
         ^~~~~~
src/imagine/bpg.cpp:83:9: note: suggested alternative: 'fread_s'
         reader.LoadFromBuffer (loadParam->buffer, loadParam->length);
         ^~~~~~
         fread_s
src/imagine/bpg.cpp:85:9: error: 'BpgDecoder' was not declared in this scope
         BpgDecoder &decoder = reader.GetDecoder();
         ^~~~~~~~~~
src/imagine/bpg.cpp:85:21: error: 'decoder' was not declared in this scope
         BpgDecoder &decoder = reader.GetDecoder();
                     ^~~~~~~
src/imagine/bpg.cpp:86:15: error: 'BpgImageInfo2' does not name a type; did you mean 'BPGImageInfo'?
         const BpgImageInfo2 &info = decoder.GetInfo();
               ^~~~~~~~~~~~~
               BPGImageInfo
src/imagine/bpg.cpp:87:19: error: 'info' was not declared in this scope
         int bpp = info.GetBpp();
                   ^~~~
src/imagine/bpg.cpp:87:19: note: suggested alternative: 'int'
         int bpp = info.GetBpp();
                   ^~~~
                   int
src/imagine/bpg.cpp:88:9: error: 'Logi' was not declared in this scope
         Logi ("%s [%ux%u] @ %u bpp flags%X\n", __FUNCTION__, info.width, info.height, bpp, flags);
         ^~~~
src/imagine/bpg.cpp:144:9: error: 'Loge' was not declared in this scope
         Loge (e.what());
         ^~~~
src/imagine/bpg.cpp: In function 'BOOL registerProcA(const IMAGINEPLUGININTERFACE*)':
src/imagine/bpg.cpp:167:64: error: cast from 'IMAGINEFILEINFO*' to 'BOOL {aka int}' loses precision [-fpermissive]
     return (BOOL)iface->lpVtbl->RegisterFileType(&fileInfoItemA);
                                                                ^
src/imagine/bpg.cpp: In function 'BOOL registerProcW(const IMAGINEPLUGININTERFACE*)':
src/imagine/bpg.cpp:181:64: error: cast from 'IMAGINEFILEINFO*' to 'BOOL {aka int}' loses precision [-fpermissive]
     return (BOOL)iface->lpVtbl->RegisterFileType(&fileInfoItemW);
                                                                ^
src/imagine/bpg.cpp: In function 'BOOL DllMain(HINSTANCE, DWORD, LPVOID)':
src/imagine/bpg.cpp:190:9: error: 'Logi' was not declared in this scope
         Logi ("Compiled at %s %s\n", __TIME__, __DATE__);
         ^~~~
src/imagine/bpg.cpp:191:9: error: 'BpgReader' has not been declared
         BpgReader::InitClass();
         ^~~~~~~~~
src/imagine/bpg.cpp:195:9: error: 'BpgReader' has not been declared
         BpgReader::DeinitClass();
         ^~~~~~~~~
make: *** [Makefile:123: obj/imagine/bpg.cpp.o] Error 1

**Comment by leavinel** [comment]
Hi,
I haven't tried to compile my codes in mingw-x64.
It seems that some part of codes is not compatible with x64 WINAPI. I will try to fix it later.

**Comment by leavinel** [comment]
x64 build released [0.0.0.5](https://github.com/leavinel/BPG-Plugins/releases/tag/v0.0.0.5)
