### ISSUE TITLE
Imagine plugins don't work/load

### ISSUE THREAD

**Issue by ianamk** [leavinel/BPG-Plugins#8]
First of tanks for the x64 port
I just downloaded the plugins and while I can report that the xnview plugin works fine with xnviewmp-x64 non of the imagine plugins work (they don't load in imagine)
here's a few screenshots 
I copied the plugins in the imagine plugin folder (I have other imagine plugins installed)
![clipboard01](https://user-images.githubusercontent.com/28848990/32588166-26d7ada2-c50d-11e7-9f82-4bdec34ab9af.png)
but they don't show in Imagine's installed plugins list niether in the 32 or the 64 bit version
![clipboard02](https://user-images.githubusercontent.com/28848990/32588175-3a09d65c-c50d-11e7-8dab-71ea659cc48d.png)

![clipboard03](https://user-images.githubusercontent.com/28848990/32588181-3fd02f82-c50d-11e7-8394-3464facda98a.png)

I'm using the latest Imagine 1.1.0
![clipboard04](https://user-images.githubusercontent.com/28848990/32588211-7fb26868-c50d-11e7-80cb-020779f22a8a.png)

one more thing the imagine author changed the imagine url 
http://www.nyam.pe.kr/blog/entry/Imagine no longer works the proper url for imagine is
http://www.nyam.pe.kr/dev/imagine/

**Comment by leavinel** [comment]
https://github.com/leavinel/BPG-Plugins/wiki#imagine-64-bit
Please check step 3 & 4

**Comment by ianamk** [comment]
yes my mistake copying the dll's solves that issue
but unfortunately both x32 and x64 dlls have the same name meaning you can't have both 32 and 64 bit plugin in the same folder
maybe change the dll names to avutil-55-x64.dll or do a static compile
I'll close this issue and try patching the plg64 files so I can keep both plugins in the same folder

edit unfortunately swscale-4.dll depends on avutil-55.dll so if I'd patch bpg.plg64 to load swscale-4-x64.dll I'd have to patch swscale-4-x64.dll to load avutil-55-x64.dll so a simple name change is not that simple, I would separate the 32 from the 64 bit version of imagine but unfortunately that's not how TotalCommander handle's plugins it expects them to be in the same folder with a different extension wlx for 32 bit and wlx64 for 64bit, Imagine started out as a plugin
I'd like to ask for a static build (if it's possible)

**Comment by leavinel** [comment]
It's nonsense.  Normal users won't download both 32&64 bit version of software **AND** copy then into the same directory.  Why have you to do this?

BTW libbpg itself is statically linked to older version of avutil.  So plugins must be dynamically linked to swscale-4.dll

**Comment by ianamk** [comment]
not for total commander plugins (which imagine is) both 32 and 64bit versions go into the same folder that's why 32bit imagine plugins have a plg suffix and 64bit have a plg64 suffix 
even tho imagine the 32 and 64bit builds of imagine (Imagine.wlx and Imagine.wlx64) come in separate zips they're expected to be in the same folder as total commander does not usually register 64bit plugins but has a [ListerPlugins64] field with bool values for wlx files which is 1 if a plugin is 64bit and this is a reason why both imagine.wlx and imagine.wlx64 need to be in a same folder and share the plugins subfolder
I understand where you're coming from but keep in mind that imagine started out as a tc plugin and most of it's userbase are tc users your current config is unusable for tc users
you don't have to statically link them you can rename the 64bit dll's and change the dll call in the 64bit version but that would require you to recompile swscale-4.dll and change it;s load call

**Comment by leavinel** [comment]
No, it's still weird.  What you need is a TC plugin, not an Imagine plugin.
I'll consider to add TC support later
