### ISSUE TITLE
Error opening when double clicking on the file in Imagine.

### ISSUE THREAD

**Issue by EDSln** [leavinel/BPG-Plugins#9]
Error "Unsupported type"opening when double clicking on the file. If you start the program first and then open the file, it opens.

**Comment by leavinel** [comment]
Confirmed, but I have no idea.  It works well on XnView.
Can you try other Imagine plugins to see if it happens?

**Comment by EDSln** [comment]
Other plugins work, but they do not need dll's. Apparently the problem is in catching dll. v0003 works fine, but there is no 64 bit version.

**Comment by leavinel** [comment]
It seems to be a problem on DLL path.
2 workarounds:
- Copy avutil-55.dll & swscale-4.dll into C:\WINDOWS\system32
- Add Imagine dir to your PATH environment variable

**Comment by EDSln** [comment]
Thank you! It works now.
